"""add excel metadata to intake submissions

Revision ID: bf0739fa6ab4
Revises: 389f85fa2691
Create Date: 2026-08-06 19:17:00.516181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0739fa6ab4'
down_revision: Union[str, Sequence[str], None] = '389f85fa2691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "intake_submissions",
    sa.Column(
        "excel_upload_status",
        sa.String(length=30),
        nullable=False,
        server_default="pending",
    ),
)
    op.alter_column(
    "intake_submissions",
    "excel_upload_status",
    server_default=None,
)
    op.add_column('intake_submissions', sa.Column('excel_filename', sa.String(length=300), nullable=True))
    op.add_column('intake_submissions', sa.Column('excel_file_id', sa.String(length=300), nullable=True))
    op.add_column('intake_submissions', sa.Column('excel_web_view_link', sa.String(length=1000), nullable=True))
    op.add_column('intake_submissions', sa.Column('excel_upload_error', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake_submissions', 'excel_upload_error')
    op.drop_column('intake_submissions', 'excel_web_view_link')
    op.drop_column('intake_submissions', 'excel_file_id')
    op.drop_column('intake_submissions', 'excel_filename')
    op.drop_column('intake_submissions', 'excel_upload_status')
    # ### end Alembic commands ###
