"""allow reuse of cancelled appointment slots

Revision ID: c3100a8363c3
Revises: bf0739fa6ab4
Create Date: 2026-08-07 12:53:57.110766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3100a8363c3'
down_revision: Union[str, Sequence[str], None] = 'bf0739fa6ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_appointments_starts_at'), 'appointments', type_='unique')
    op.create_index('uq_appointments_active_starts_at', 'appointments', ['starts_at'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_appointments_active_starts_at', table_name='appointments', postgresql_where=sa.text("status IN ('pending', 'confirmed')"))
    op.create_unique_constraint(op.f('uq_appointments_starts_at'), 'appointments', ['starts_at'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
